CREATE TABLE IF NOT EXISTS energy_level (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  isin VARCHAR(250),
  elvl REAL NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS isin ON energy_level(isin);

CREATE TABLE IF NOT EXISTS quote (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  isin VARCHAR(250) NOT NULL,
  bid REAL NULL,
  ask REAL NULL
);